<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ImagesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    private $bookTitles = [
        'Murder on the Orient Express',
        'And Then There Were None',
        'The Murder of Roger Ackroyd',
        'Midwinter Murder',
        'The Mysterious Affair at Styles',
        'Death on the Nile',
        'The Murder at the Vicarage',
        'The Hollow',
        'A Murder Is Announced',
        'Sparkling Cyanide',
        'The Adventures Of Sherlock Holmes',
        'The Hound of the Baskervilles',
        'A Study in Scarlet',
        'The Memoirs of Sherlock Holmes',
        'The Sign of Four',
        'Notes from a Small Island',
        'A Short History of Nearly Everything',
        'A Walk in the Woods: Rediscovering America on the Appalachian Trail',
        'In a Sunburned Country',
        'The Road to Little Dribbling: Adventures of an American in Britain',
        'One Summer: America, 1927',
        'I\'m a Stranger Here Myself: Notes on Returning to America After 20 Years Away',
        'Bill Bryson\'s African Diary',
        'Neither here nor there: Travels in Europe',
        'The Lost Continent: Travels in Small Town America',
        'The Great Railway Bazaar',
        'Deep South: Four Seasons on Back Roads',
        'The Happy Isles of Oceania: Paddling the Pacific',
        'On The Plain Of Snakes: A Mexican Journey',
        'The Old Patagonian Express: By Train Through the Americas',
        'How to Win Friends and Influence People',
        'How to Stop Worrying & Start Living',
        'The Art of Public Speaking: The Original Tool for Improving Public Oration',
        'Take Command',
        'The Quick and Easy Way to Effective Speaking',
        'Listen!: The Art of Effective Communication',
        'Make Yourself Unforgettable',
        'How To Develop Self-Confidence & Influence People',
        'How to Stop Worrying and Start Living',
        '3 Steps to Being a Great Manager',
        'Life Force',
        'MONEY Master the Game: 7 Simple Steps to Financial',
        'Unshakable: Your Financial Freedom Playbook',
        'The Path: Accelerating Your Journey to Financial Freedom',
        'The Emotion Code',
        'Mastering the Art of French Cooking',
        'Mastering the Art of French Cooking, Volume 2',
        'The French Chef Cookbook',
        'Julia\'s Kitchen Wisdom',
        'People Who Love to Eat Are Always the Best People',
        'The Way to Cook',
        'Julia and Jacques Cooking at Home',
        'My Life in France',
        'Baking with Julia',
        'Julia\'s Breakfasts, Lunches, and Suppers: Seven menus for the three main meals',
        'One: Simple One-Pan Wonders',
        '5 Ingredients: Quick & Easy Food',
        'Jamie\'s 30-Minute Meals',
        'Together: Memorable Meals Made Easy',
        'Ultimate Veg',
        'Hackers',
        'In the Plex',
        'Crypto',
        'Facebook: The Inside Story',
        'Insanely Great',
        'The Code Breaker',
        'The Wise Men: Six Friends and the World They Made',
        'The Innovators',
        'Leonardo da Vinci',
        'Einstein: His Life and Universe',
        'Green Eggs and Ham',
        'Oh, the Places You\'ll Go!',
        'One Fish Two Fish Red Fish Blue Fish',
        'The Cat in the Hat',
        'How the Grinch Stole Christmas',
        'Fox in Socks',
        'The Sneetches and Other Stories',
        'The Lorax',
        'Dr. Seuss\'s ABC',
        'Hop on Pop',
        'Matilda',
        'Charlie and the Chocolate Factory',
        'James and the Giant Peach',
        'The BFG',
        'Charlie and the Great Glass Elevator',
        'Dreamland',
        'The Wish',
        'Every Breath',
        'The Return',
        'The Rescue',
        'A Bend in the Road',
        'True Believer',
        'The Guardian',
        'See Me',
        'Two by Two',
        'The Choice: The Dragon Heart Legacy',
        'The Becoming: The Dragon Heart Legacy',
        'The Awakening: The Dragon Heart Legacy',
        'Nightwork',
        'Courting Catherine: The Calhoun Women',
        'Truman',
        'The Path Between the Seas',
        'The Pioneers',
        '1776',
        'The Great Bridge',
        'The Wright Brothers',
        'John Adams',
        'Brave Companions',
        'Mornings on Horseback',
        'Johnstown Flood',
        'Team of Rivals',
        'No Ordinary Time',
        'Leadership',
        'The Bully Pulpit',
        'Lincoln',
        'David and Goliath',
        'Talking to Strangers',
        'Outliers',
        'Blink',
        'The Tipping Point',
        'The Big Shor',
        'Liar\'s Poker',
        'Moneyball',
        'The Fifth Risk',
        'The Undoing Project',
        'Harry Potter and the Prisoner of Azkaban',
        'Harry Potter and the Goblet of Fire',
        'Harry Potter and the Half-Blood Prince',
        'Harry Potter and the Order of the Phoenix',
        'Harry Potter and the Sorcerer\'s Stone',
        'Fairy Tale',
        'Billy Summers',
        'The Dark Tower I: The Gunslinger',
        'The Institute',
        'The Shining',
        'Gwendy\'s Final Task',
        'The Outsider',
        'Mr. Mercedes',
        '\'Salem\'s Lot',
        'It',
    ];

    public function run(): void
    {
        $now = now();
        foreach ($this->bookTitles as $key => $value) {
            DB::table('images')->insert([
                'src' => $key + 1 . '.jpg',
                'alt' => $value . ' image',
                'created_at' => $now,
                'updated_at' => $now
            ]);
        }
    }
}
